operations:
  view:
    - type: web
      impl: index.html
actions: actions
web: web-src
runtimeManifest:
  packages:
    dx-excshell-1:
      license: Apache-2.0
      actions:
        get-presigned-storage-url:
          function: actions/get-presigned-storage-url/index.js
          web: 'yes'
          runtime: 'nodejs:14'
          inputs:
            LOG_LEVEL: debug
          annotations:
            require-adobe-auth: true
            final: true
